version: "3.8"

services:
  product-postgres:
    image: postgres
    container_name: product_postgres
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    expose:
      - "54322"
    ports:
      - "54322:54322"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - product-volume:/var/lib/postgresql/data
    command: -p 54322
volumes:
  product-volume:





